name: SUES Health Information

on: 
  push:
    branches: [ master ]
  schedule:
    - cron: '15,30,45 0-9 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Python Dependencies. 
      run: |
        python -m pip install --upgrade pip
        pip install BeautifulSoup4
        pip install Requests
        pip install lxml
    
    - name: Run Script to Fill in SUES Health Information Automaticly by Using GitHub Action! 
      run: python sues_health_information_3.0.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}      
